In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.decomposition import PCA 
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import normalize

In [2]:
# Importing the dataset
dataset = pd.read_csv('Datasets/APAC/NSE.csv')
dataset = dataset.drop(['Unnamed: 0', 'Exchange'], axis = 1) 
dataset = dataset.dropna()
X = dataset.iloc[:,1:]

# Preprocessing
scaler = StandardScaler()
X = scaler.fit_transform(X)

X = normalize(X) 

pca = PCA(n_components = 1) 
X_principal = pca.fit_transform(X) 
X_principal = pd.DataFrame(X_principal) 

X = X_principal.values

# Fitting K-Means to the dataset
for n in range(2,13,1):
    kmeans = KMeans(n_clusters = n, init = 'k-means++', random_state = 42)
    y_kmeans = kmeans.fit_predict(X)

    print('Silhouette Score(n={}): {}'.format(n, silhouette_score(X, y_kmeans)))

Silhouette Score(n=2): 0.5982949545894997
Silhouette Score(n=3): 0.660070531942042
Silhouette Score(n=4): 0.6295775596639392
Silhouette Score(n=5): 0.6010724647510423
Silhouette Score(n=6): 0.5648323864726107
Silhouette Score(n=7): 0.5753839484654966
Silhouette Score(n=8): 0.572346428787331
Silhouette Score(n=9): 0.5604273514993473
Silhouette Score(n=10): 0.55330290664271
Silhouette Score(n=11): 0.5444447364390193
Silhouette Score(n=12): 0.5345066345755117

In [3]:
kmeans = KMeans(n_clusters = 3, init = 'k-means++', random_state = 42)
y_kmeans = kmeans.fit_predict(X)

dataset['Cluster'] = y_kmeans
dataset.head(3)

,Symbol,grossProfitRatioQMinus1,grossProfitRatioQMinus2,epsdilutedQMinus1,epsdilutedQMinus2,priceEarningsToGrowthRatioTTM,priceCashFlowRatioTTM,priceEarningsRatioTTM,priceBookValueRatioTTM,assetTurnoverTTM,dividendYieldPercentageTTM,Cluster
0,MRF.NS,0.402544,0.427952,31.73002,1601.02802,0.013913,31.621018,22.269816,2.119940,0.731869,0.163820,2
1,HONAUT.NS,0.509759,0.540028,110.93002,125.70649,0.355395,138.451860,44.673481,12.091219,1.164501,0.251776,2
2,SHREECEM.NS,0.748280,0.736673,91.34999,148.56126,0.345743,139.842596,51.355057,5.793897,0.603974,0.189148,1